# Generated by Django 2.2a1 on 2020-11-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=75, null=True)),
                ('uf', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
