# Generated by Django 2.2a1 on 2020-11-09 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conectapet', '0003_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('rate', models.CharField(blank=True, choices=[('Gratuito', 'Gratuito'), ('10,00', '10,00'), ('15,00', '15,00'), ('20,00', '20,00'), ('25,00', '25,00'), ('30,00', '30,00'), ('35,00', '35,00'), ('40,00', '40,00'), ('45,00', '45,00'), ('50,00', '50,00'), ('55,00', '55,00'), ('60,00', '60,00'), ('65,00', '65,00'), ('70,00', '70,00'), ('75,00', '75,00'), ('80,00', '80,00'), ('85,00', '85,00'), ('90,00', '90,00'), ('95,00', '95,00'), ('100,00', '100,00')], default='Gratuito', max_length=8, null=True)),
                ('hour_open', models.CharField(blank=True, choices=[('06:00', '06:00'), ('06:30', '06:30'), ('07:00', '07:00'), ('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30')], default='', max_length=5, null=True)),
                ('hour_close', models.CharField(blank=True, choices=[('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30')], default='', max_length=5, null=True)),
                ('mission_statement', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('web_site', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number_ddd', models.CharField(blank=True, choices=[('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('21', '21'), ('22', '22'), ('24', '24'), ('27', '27'), ('28', '28'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('37', '37'), ('38', '38'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('51', '51'), ('53', '53'), ('54', '54'), ('55', '55'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'), ('69', '69'), ('71', '71'), ('73', '73'), ('74', '74'), ('75', '75'), ('77', '77'), ('79', '79'), ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'), ('87', '87'), ('88', '88'), ('89', '89'), ('91', '91'), ('92', '92'), ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'), ('99', '99')], max_length=3, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=40, null=True)),
                ('logo_link', models.ImageField(blank=True, null=True, upload_to='')),
                ('picture_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('picture_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_foster_ok', models.BooleanField(default=0)),
                ('is_volunteer_ok', models.BooleanField(default=0)),
                ('has_transportation', models.BooleanField(default=0)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('founded_date', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('is_approved', models.BooleanField(default=0)),
                ('transportation_price', models.CharField(blank=True, choices=[('Grtis', 'Grtis'), ('1,00', '1,00'), ('2,00', '2,00'), ('3,00', '3,00'), ('4,00', '4,00'), ('5,00', '5,00'), ('7,00', '7,00'), ('10,00', '10,00'), ('12,00', '12,00'), ('15,00', '15,00'), ('18,00', '18,00'), ('20,00', '20,00'), ('25,00', '25,00'), ('30,00', '30,00'), ('35,00', '35,00'), ('40,00', '40,00'), ('45,00', '45,00'), ('50,00', '50,00'), ('55,00', '65,00'), ('60,00', '60,00')], max_length=7, null=True)),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conectapet.Cidade')),
                ('state_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conectapet.Estado')),
            ],
        ),
    ]
