# Generated by Django 2.2a1 on 2020-11-09 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conectapet', '0006_pet_pet_disease_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnose_date', models.DateField(blank=True, null=True)),
                ('disease_status', models.CharField(blank=True, choices=[('Curado', 'Curado'), ('Em tratamento', 'Em tratamento'), ('Sem verba', 'Sem verba')], default='', max_length=100, null=True)),
                ('disease_type', models.CharField(blank=True, choices=[('Fatal', 'Fatal'), ('Para o resto da vida', 'Para o resto da vida'), ('Temporria', 'Temporria')], default='', max_length=100, null=True)),
                ('internal_notes', models.CharField(blank=True, max_length=300, null=True)),
                ('which_special_need', models.CharField(blank=True, choices=[('3 patas funcionais', '3 patas funcionais'), ('2 patas funcionais', '2 patas funcionais'), ('1 pata funcional', '1 pata funcional'), ('0 patas funcionais', '0 patas funcionais'), ('No pode mastigar', 'No pode mastigar'), ('Cegueira parcial', 'Cegueira parcial'), ('Cegueira total', 'Cegueira total'), ('Necessidade de remdios para sempre', 'Necessidade de remdios para sempre'), ('Necessidade de terapias para sempre', 'Necessidade de terapias'), ('Necessidade de terapias e remdios para sempre', 'Necessidade de terapias e remdios para sempre'), ('Doena mental', 'Doena mental'), ('Epilepsia', 'Epilesia'), ('Rabo amputado', 'Rabo amputado'), ('Surdez parcial', 'Surdez parcial'), ('Surdez total', 'Surdez total'), ('No sente cheiro', 'No sente cheiro')], default='', max_length=100, null=True)),
                ('which_special_treatment', models.CharField(blank=True, choices=[('Fisioterapia', 'Fisioterapia'), ('Acunpuntura', 'Acunpuntura'), ('Caminhada diria', 'Caminhada diria')], default='', max_length=100, null=True)),
                ('disease_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conectapet.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('area', models.CharField(blank=True, choices=[('Cardiologia', 'Cardiologia'), ('Dermatologia', 'Dermatologia'), ('Endocrinologia', 'Endocrinologia'), ('Gastroenterologia e Hepatologia', 'Gastroenterologia e Hepatologia'), ('Hematologia e Imunologia', 'Hematologia e Imunologia'), ('Infecciosas', 'Infecciosas'), ('Intoxicaes e Envenemanentos', 'Intoxicaes e Envenemanentos'), ('Musculoesquelticas', 'Musculoesquelticas'), ('Nefrologia e Urologia', 'Nefrologia e Urologia'), ('Neonatologia', 'Neonatologia'), ('Neurologia', 'Neurologia'), ('Oftalmologia', 'Oftalmologia'), ('Oncologia', 'Oncologia'), ('Respiratrias', 'Respiratrias'), ('Teriogenologia', 'Teriogenologia'), ('Vacinao e Nutrologia', 'Vacinao e Nutrologia'), ('Outras', 'Outras')], default='', max_length=100, null=True)),
                ('area_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conectapet.Pet_disease_areas')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conectapet.Pet')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
