# Generated by Django 2.2a1 on 2021-03-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectapet', '0007_favorites_pet_disease_pet_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth_year',
            field=models.IntegerField(blank=True, choices=[(2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991)], default=0, null=True),
        ),
    ]
